[package]
name = "saes-api"
version = "2.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
sea-orm = { version = "1.1.10", features = [
    "sqlx-mysql",
    "runtime-tokio-native-tls",
    "macros",
] }
serde_json = "1.0.140"
sha2 = "0.10.8"
axum = { version = "0.8.3", features = ["http2", "macros", "multipart"] }
tokio = { version = "1.44.2", features = ["full"] }
tower-cookies = "0.11.0"
dotenvy = "0.15.7"
reqwest = { version = "0.12.15", features = ["json"] }
url-builder = "0.1.1"
tower-http = { version = "0.6.2", features = ["cors", "fs", "trace"] }
chrono = "0.4.40"
http = "1.3.1"
socketioxide = "0.16.2"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
tower = "0.5.2"
base64 = "0.22.1"
saes-shared = { path = "../shared" }
lazy_static = "1.5.0"
random-string = "1.1.0"
rand = { version = "0.9.1", features = ["serde"] }
jsonwebtoken = "9.3.1"
cookie = "0.18.1"
